---
dist: xenial
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: debian9

# Cache Ansible and Molecule to speed things up
cache:
  - pip

install:
  # Install Ansible, Molecule and docker-py
  - pip install ansible molecule docker

  # Log Docker, Ansible and Molecule version
  - docker --version
  - ansible --version
  - molecule --version

before_script:
  - cd .. && mv ansible-role-backports jgeusebroek.backports && cd jgeusebroek.backports

script:
  # Start test
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
