---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: False
  options:
    config-file: ../../../resources/.yamllint
platforms:
    - name: debian8
      image: jgeusebroek/debian8-molecule
      image_version: latest
      ansible_groups:
        - debian
    - name: debian9
      image: jgeusebroek/debian9-molecule
      image_version: latest
      ansible_groups:
        - debian
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
